# This file is a general .xdc for the Nexys A7-100T
# To use it in a project:
# - uncomment the lines corresponding to used pins
# - rename the used ports (in each line, after get_ports) according to the top level signal names in the project
# Note: As the Nexys 4 DDR was rebranded to the Nexys A7 with no substantial changes, this XDC file will also work for the Nexys 4 DDR.

# Clock signal
# Pin name = IO_L12P_T1_MRCC_35, Sch name = clock
set_property PACKAGE_PIN E3 [get_ports {clock}]
set_property IOSTANDARD LVCMOS33 [get_ports {clock}]
create_clock -add -name sys_clk_pin -period 10 -waveform {0 5} [get_ports {clock}];


#Switches
# Pin name = IO_L24N_T3_RS0_15, Sch name = SW[0]
set_property PACKAGE_PIN J15 [get_ports {SW[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[0]}]
# Pin name = IO_L3N_T0_DQS_EMCCLK_14, Sch name = SW[1]
set_property PACKAGE_PIN L16 [get_ports {SW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[1]}]
# Pin name = IO_L6N_T0_D08_VREF_14, Sch name = SW[2]
set_property PACKAGE_PIN M13 [get_ports {SW[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[2]}]
# Pin name = IO_L13N_T2_MRCC_14, Sch name = SW[3]
set_property PACKAGE_PIN R15 [get_ports {SW[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[3]}]
# Pin name = IO_L12N_T1_MRCC_14, Sch name = SW[4]
set_property PACKAGE_PIN R17 [get_ports {SW[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[4]}]
# Pin name = IO_L7N_T1_D10_14, Sch name = SW[5]
set_property PACKAGE_PIN T18 [get_ports {SW[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[5]}]
# Pin name = IO_L17N_T2_A13_D29_14, Sch name = SW[6]
set_property PACKAGE_PIN U18 [get_ports {SW[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[6]}]
# Pin name = IO_L5N_T0_D07_14, Sch name = SW[7]
set_property PACKAGE_PIN R13 [get_ports {SW[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[7]}]
# Pin name = IO_L24N_T3_34, Sch name = SW[8]
set_property PACKAGE_PIN T8 [get_ports {SW[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[8]}]
# Pin name = IO_25_34, Sch name = SW[9]
set_property PACKAGE_PIN U8 [get_ports {SW[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[9]}]
# Pin name = IO_L15P_T2_DQS_RDWR_B_14, Sch name = SW[10]
set_property PACKAGE_PIN R16 [get_ports {SW[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[10]}]
# Pin name = IO_L23P_T3_A03_D19_14, Sch name = SW[11]
set_property PACKAGE_PIN T13 [get_ports {SW[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[11]}]
# Pin name = IO_L24P_T3_35, Sch name = SW[12]
set_property PACKAGE_PIN H6 [get_ports {SW[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[12]}]
# Pin name = IO_L20P_T3_A08_D24_14, Sch name = SW[13]
set_property PACKAGE_PIN U12 [get_ports {SW[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[13]}]
# Pin name = IO_L19N_T3_A09_D25_VREF_14, Sch name = SW[14]
set_property PACKAGE_PIN U11 [get_ports {SW[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[14]}]
# Pin name = IO_L21P_T3_DQS_14, Sch name = SW[15]
set_property PACKAGE_PIN V10 [get_ports {SW[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[15]}]

# LEDs
# Pin name = IO_L18P_T2_A24_15, Sch name = LED[0]
set_property PACKAGE_PIN H17 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
# Pin name = IO_L24P_T3_RS1_15, Sch name = LED[1]
set_property PACKAGE_PIN K15 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
# Pin name = IO_L17N_T2_A25_15, Sch name = LED[2]
set_property PACKAGE_PIN J13 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
# Pin name = IO_L8P_T1_D11_14, Sch name = LED[3]
set_property PACKAGE_PIN N14 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
# Pin name = IO_L7P_T1_D09_14, Sch name = LED[4]
set_property PACKAGE_PIN R18 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
# Pin name = IO_L18N_T2_A11_D27_14, Sch name = LED[5]
set_property PACKAGE_PIN V17 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
# Pin name = IO_L17P_T2_A14_D30_14, Sch name = LED[6]
set_property PACKAGE_PIN U17 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
# Pin name = IO_L18P_T2_A12_D28_14, Sch name = LED[7]
set_property PACKAGE_PIN U16 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
# Pin name = IO_L16N_T2_A15_D31_14, Sch name = LED[8]
set_property PACKAGE_PIN V16 [get_ports {LED[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[8]}]
# Pin name = IO_L14N_T2_SRCC_14, Sch name = LED[9]
set_property PACKAGE_PIN T15 [get_ports {LED[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[9]}]
# Pin name = IO_L22P_T3_A05_D21_14, Sch name = LED[10]
set_property PACKAGE_PIN U14 [get_ports {LED[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[10]}]
# Pin name = IO_L15N_T2_DQS_DOUT_CSO_B_14, Sch name = LED[11]
set_property PACKAGE_PIN T16 [get_ports {LED[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[11]}]
# Pin name = IO_L16P_T2_CSI_B_14, Sch name = LED[12]
set_property PACKAGE_PIN V15 [get_ports {LED[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[12]}]
# Pin name = IO_L22N_T3_A04_D20_14, Sch name = LED[13]
set_property PACKAGE_PIN V14 [get_ports {LED[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[13]}]
# Pin name = IO_L20N_T3_A07_D23_14, Sch name = LED[14]
set_property PACKAGE_PIN V12 [get_ports {LED[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[14]}]
# Pin name = IO_L21N_T3_DQS_A06_D22_14, Sch name = LED[15]
set_property PACKAGE_PIN V11 [get_ports {LED[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[15]}]

# # RGB LEDs
# # Pin name = IO_L5P_T0_D06_14, Sch name = LED16_B
# set_property PACKAGE_PIN R12 [get_ports {LED16_B}]
# set_property IOSTANDARD LVCMOS33 [get_ports {LED16_B}]
# # Pin name = IO_L10P_T1_D14_14, Sch name = LED16_G
# set_property PACKAGE_PIN M16 [get_ports {LED16_G}]
# set_property IOSTANDARD LVCMOS33 [get_ports {LED16_G}]
# # Pin name = IO_L11P_T1_SRCC_14, Sch name = LED16_R
# set_property PACKAGE_PIN N15 [get_ports {LED16_R}]
# set_property IOSTANDARD LVCMOS33 [get_ports {LED16_R}]
# # Pin name = IO_L15N_T2_DQS_ADV_B_15, Sch name = LED17_B
# set_property PACKAGE_PIN G14 [get_ports {LED17_B}]
# set_property IOSTANDARD LVCMOS33 [get_ports {LED17_B}]
# # Pin name = IO_0_14, Sch name = LED17_G
# set_property PACKAGE_PIN R11 [get_ports {LED17_G}]
# set_property IOSTANDARD LVCMOS33 [get_ports {LED17_G}]
# # Pin name = IO_L11N_T1_SRCC_14, Sch name = LED17_R
# set_property PACKAGE_PIN N16 [get_ports {LED17_R}]
# set_property IOSTANDARD LVCMOS33 [get_ports {LED17_R}]

# #7 segment display
# # Pin name = IO_L24N_T3_A00_D16_14, Sch name = SEG[0]
# set_property PACKAGE_PIN T10 [get_ports {SEG[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {SEG[0]}]
# # Pin name = IO_25_14, Sch name = SEG[1]
# set_property PACKAGE_PIN R10 [get_ports {SEG[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {SEG[1]}]
# # Pin name = IO_25_15, Sch name = SEG[2]
# set_property PACKAGE_PIN K16 [get_ports {SEG[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {SEG[2]}]
# # Pin name = IO_L17P_T2_A26_15, Sch name = SEG[3]
# set_property PACKAGE_PIN K13 [get_ports {SEG[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {SEG[3]}]
# # Pin name = IO_L13P_T2_MRCC_14, Sch name = SEG[4]
# set_property PACKAGE_PIN P15 [get_ports {SEG[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {SEG[4]}]
# # Pin name = IO_L19P_T3_A10_D26_14, Sch name = SEG[5]
# set_property PACKAGE_PIN T11 [get_ports {SEG[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {SEG[5]}]
# # Pin name = IO_L4P_T0_D04_14, Sch name = SEG[6]
# set_property PACKAGE_PIN L18 [get_ports {SEG[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {SEG[6]}]
# # # Pin name = IO_L19N_T3_A21_VREF_15, Sch name = DP
# # set_property PACKAGE_PIN H15 [get_ports {DP}]
# # set_property IOSTANDARD LVCMOS33 [get_ports {DP}]
# # Pin name = IO_L23P_T3_FOE_B_15, Sch name = AN[0]
# set_property PACKAGE_PIN J17 [get_ports {AN[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]
# # Pin name = IO_L23N_T3_FWE_B_15, Sch name = AN[1]
# set_property PACKAGE_PIN J18 [get_ports {AN[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
# # Pin name = IO_L24P_T3_A01_D17_14, Sch name = AN[2]
# set_property PACKAGE_PIN T9 [get_ports {AN[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
# # Pin name = IO_L19P_T3_A22_15, Sch name = AN[3]
# set_property PACKAGE_PIN J14 [get_ports {AN[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]
# # Pin name = IO_L8N_T1_D12_14, Sch name = AN[4]
# set_property PACKAGE_PIN P14 [get_ports {AN[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {AN[4]}]
# # Pin name = IO_L14P_T2_SRCC_14, Sch name = AN[5]
# set_property PACKAGE_PIN T14 [get_ports {AN[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {AN[5]}]
# # Pin name = IO_L23P_T3_35, Sch name = AN[6]
# set_property PACKAGE_PIN K2 [get_ports {AN[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {AN[6]}]
# # Pin name = IO_L23N_T3_A02_D18_14, Sch name = AN[7]
# set_property PACKAGE_PIN U13 [get_ports {AN[7]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {AN[7]}]

# #CPU Reset Button
# # Pin name = IO_L3P_T0_DQS_AD1P_15, Sch name = CPU_RESETN
# set_property PACKAGE_PIN C12 [get_ports {CPU_RESETN}]
# set_property IOSTANDARD LVCMOS33 [get_ports {CPU_RESETN}]

# #Buttons
# # Pin name = IO_L9P_T1_DQS_14, Sch name = BTNC
# set_property PACKAGE_PIN N17 [get_ports {BTNC}]
# set_property IOSTANDARD LVCMOS33 [get_ports {BTNC}]
# # Pin name = IO_L4N_T0_D05_14, Sch name = BTNU
# set_property PACKAGE_PIN M18 [get_ports {BTNU}]
# set_property IOSTANDARD LVCMOS33 [get_ports {BTNU}]
# # Pin name = IO_L12P_T1_MRCC_14, Sch name = BTNL
# set_property PACKAGE_PIN P17 [get_ports {BTNL}]
# set_property IOSTANDARD LVCMOS33 [get_ports {BTNL}]
# # Pin name = IO_L10N_T1_D15_14, Sch name = BTNR
# set_property PACKAGE_PIN M17 [get_ports {BTNR}]
# set_property IOSTANDARD LVCMOS33 [get_ports {BTNR}]
# # Pin name = IO_L9N_T1_DQS_D13_14, Sch name = BTND
# set_property PACKAGE_PIN P18 [get_ports {BTND}]
# set_property IOSTANDARD LVCMOS33 [get_ports {BTND}]


# #Pmod Headers
# #Pmod Header JA
# # Pin name = IO_L20N_T3_A19_15, Sch name = JA[1]
# set_property PACKAGE_PIN C17 [get_ports {JA[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JA[1]}]
# # Pin name = IO_L21N_T3_DQS_A18_15, Sch name = JA[2]
# set_property PACKAGE_PIN D18 [get_ports {JA[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JA[2]}]
# # Pin name = IO_L21P_T3_DQS_15, Sch name = JA[3]
# set_property PACKAGE_PIN E18 [get_ports {JA[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JA[3]}]
# # Pin name = IO_L18N_T2_A23_15, Sch name = JA[4]
# set_property PACKAGE_PIN G17 [get_ports {JA[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JA[4]}]
# # Pin name = IO_L16N_T2_A27_15, Sch name = JA[7]
# set_property PACKAGE_PIN D17 [get_ports {JA[7]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JA[7]}]
# # Pin name = IO_L16P_T2_A28_15, Sch name = JA[8]
# set_property PACKAGE_PIN E17 [get_ports {JA[8]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JA[8]}]
# # Pin name = IO_L22N_T3_A16_15, Sch name = JA[9]
# set_property PACKAGE_PIN F18 [get_ports {JA[9]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JA[9]}]
# # Pin name = IO_L22P_T3_A17_15, Sch name = JA[10]
# set_property PACKAGE_PIN G18 [get_ports {JA[10]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JA[10]}]

# #Pmod Header JB
# # Pin name = IO_L1P_T0_AD0P_15, Sch name = JB[1]
# set_property PACKAGE_PIN D14 [get_ports {JB[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JB[1]}]
# # Pin name = IO_L14N_T2_SRCC_15, Sch name = JB[2]
# set_property PACKAGE_PIN F16 [get_ports {JB[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JB[2]}]
# # Pin name = IO_L13N_T2_MRCC_15, Sch name = JB[3]
# set_property PACKAGE_PIN G16 [get_ports {JB[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JB[3]}]
# # Pin name = IO_L15P_T2_DQS_15, Sch name = JB[4]
# set_property PACKAGE_PIN H14 [get_ports {JB[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JB[4]}]
# # Pin name = IO_L11N_T1_SRCC_15, Sch name = JB[7]
# set_property PACKAGE_PIN E16 [get_ports {JB[7]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JB[7]}]
# # Pin name = IO_L5P_T0_AD9P_15, Sch name = JB[8]
# set_property PACKAGE_PIN F13 [get_ports {JB[8]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JB[8]}]
# # Pin name = IO_0_15, Sch name = JB[9]
# set_property PACKAGE_PIN G13 [get_ports {JB[9]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JB[9]}]
# # Pin name = IO_L13P_T2_MRCC_15, Sch name = JB[10]
# set_property PACKAGE_PIN H16 [get_ports {JB[10]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JB[10]}]

# #Pmod Header JC
# # Pin name = IO_L23N_T3_35, Sch name = JC[1]
# set_property PACKAGE_PIN K1 [get_ports {JC[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JC[1]}]
# # Pin name = IO_L19N_T3_VREF_35, Sch name = JC[2]
# set_property PACKAGE_PIN F6 [get_ports {JC[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JC[2]}]
# # Pin name = IO_L22N_T3_35, Sch name = JC[3]
# set_property PACKAGE_PIN J2 [get_ports {JC[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JC[3]}]
# # Pin name = IO_L19P_T3_35, Sch name = JC[4]
# set_property PACKAGE_PIN G6 [get_ports {JC[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JC[4]}]
# # Pin name = IO_L6P_T0_35, Sch name = JC[7]
# set_property PACKAGE_PIN E7 [get_ports {JC[7]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JC[7]}]
# # Pin name = IO_L22P_T3_35, Sch name = JC[8]
# set_property PACKAGE_PIN J3 [get_ports {JC[8]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JC[8]}]
# # Pin name = IO_L21P_T3_DQS_35, Sch name = JC[9]
# set_property PACKAGE_PIN J4 [get_ports {JC[9]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JC[9]}]
# # Pin name = IO_L5P_T0_AD13P_35, Sch name = JC[10]
# set_property PACKAGE_PIN E6 [get_ports {JC[10]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JC[10]}]

# #Pmod Header JD
# # Pin name = IO_L21N_T3_DQS_35, Sch name = JD[1]
# set_property PACKAGE_PIN H4 [get_ports {JD[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JD[1]}]
# # Pin name = IO_L17P_T2_35, Sch name = JD[2]
# set_property PACKAGE_PIN H1 [get_ports {JD[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JD[2]}]
# # Pin name = IO_L17N_T2_35, Sch name = JD[3]
# set_property PACKAGE_PIN G1 [get_ports {JD[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JD[3]}]
# # Pin name = IO_L20N_T3_35, Sch name = JD[4]
# set_property PACKAGE_PIN G3 [get_ports {JD[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JD[4]}]
# # Pin name = IO_L15P_T2_DQS_35, Sch name = JD[7]
# set_property PACKAGE_PIN H2 [get_ports {JD[7]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JD[7]}]
# # Pin name = IO_L20P_T3_35, Sch name = JD[8]
# set_property PACKAGE_PIN G4 [get_ports {JD[8]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JD[8]}]
# # Pin name = IO_L15N_T2_DQS_35, Sch name = JD[9]
# set_property PACKAGE_PIN G2 [get_ports {JD[9]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JD[9]}]
# # Pin name = IO_L13N_T2_MRCC_35, Sch name = JD[10]
# set_property PACKAGE_PIN F3 [get_ports {JD[10]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {JD[10]}]

# #Pmod Header JXADC
# # Pin name = IO_L9N_T1_DQS_AD3N_15, Sch name = XA_N[1]
# set_property PACKAGE_PIN A14 [get_ports {XA_N[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {XA_N[1]}]
# # Pin name = IO_L9P_T1_DQS_AD3P_15, Sch name = XA_P[1]
# set_property PACKAGE_PIN A13 [get_ports {XA_P[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {XA_P[1]}]
# # Pin name = IO_L8N_T1_AD10N_15, Sch name = XA_N[2]
# set_property PACKAGE_PIN A16 [get_ports {XA_N[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {XA_N[2]}]
# # Pin name = IO_L8P_T1_AD10P_15, Sch name = XA_P[2]
# set_property PACKAGE_PIN A15 [get_ports {XA_P[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {XA_P[2]}]
# # Pin name = IO_L7N_T1_AD2N_15, Sch name = XA_N[3]
# set_property PACKAGE_PIN B17 [get_ports {XA_N[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {XA_N[3]}]
# # Pin name = IO_L7P_T1_AD2P_15, Sch name = XA_P[3]
# set_property PACKAGE_PIN B16 [get_ports {XA_P[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {XA_P[3]}]
# # Pin name = IO_L10N_T1_AD11N_15, Sch name = XA_N[4]
# set_property PACKAGE_PIN A18 [get_ports {XA_N[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {XA_N[4]}]
# # Pin name = IO_L10P_T1_AD11P_15, Sch name = XA_P[4]
# set_property PACKAGE_PIN B18 [get_ports {XA_P[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {XA_P[4]}]

# #VGA Connector
# # Pin name = IO_L8N_T1_AD14N_35, Sch name = VGA_R[0]
# set_property PACKAGE_PIN A3 [get_ports {VGA_R[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]
# # Pin name = IO_L7N_T1_AD6N_35, Sch name = VGA_R[1]
# set_property PACKAGE_PIN B4 [get_ports {VGA_R[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]
# # Pin name = IO_L1N_T0_AD4N_35, Sch name = VGA_R[2]
# set_property PACKAGE_PIN C5 [get_ports {VGA_R[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]
# # Pin name = IO_L8P_T1_AD14P_35, Sch name = VGA_R[3]
# set_property PACKAGE_PIN A4 [get_ports {VGA_R[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[3]}]
# # Pin name = IO_L1P_T0_AD4P_35, Sch name = VGA_G[0]
# set_property PACKAGE_PIN C6 [get_ports {VGA_G[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]
# # Pin name = IO_L3N_T0_DQS_AD5N_35, Sch name = VGA_G[1]
# set_property PACKAGE_PIN A5 [get_ports {VGA_G[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]
# # Pin name = IO_L2N_T0_AD12N_35, Sch name = VGA_G[2]
# set_property PACKAGE_PIN B6 [get_ports {VGA_G[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]
# # Pin name = IO_L3P_T0_DQS_AD5P_35, Sch name = VGA_G[3]
# set_property PACKAGE_PIN A6 [get_ports {VGA_G[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[3]}]
# # Pin name = IO_L2P_T0_AD12P_35, Sch name = VGA_B[0]
# set_property PACKAGE_PIN B7 [get_ports {VGA_B[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]
# # Pin name = IO_L4N_T0_35, Sch name = VGA_B[1]
# set_property PACKAGE_PIN C7 [get_ports {VGA_B[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]
# # Pin name = IO_L6N_T0_VREF_35, Sch name = VGA_B[2]
# set_property PACKAGE_PIN D7 [get_ports {VGA_B[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]
# # Pin name = IO_L4P_T0_35, Sch name = VGA_B[3]
# set_property PACKAGE_PIN D8 [get_ports {VGA_B[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[3]}]
# # Pin name = IO_L4P_T0_15, Sch name = VGA_HS
# set_property PACKAGE_PIN B11 [get_ports {VGA_HS}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_HS}]
# # Pin name = IO_L3N_T0_DQS_AD1N_15, Sch name = VGA_VS
# set_property PACKAGE_PIN B12 [get_ports {VGA_VS}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_VS}]

# #Micro SD Connector
# # Pin name = IO_L14P_T2_SRCC_35, Sch name = SD_RESET
# set_property PACKAGE_PIN E2 [get_ports {SD_RESET}]
# set_property IOSTANDARD LVCMOS33 [get_ports {SD_RESET}]
# # Pin name = IO_L9N_T1_DQS_AD7N_35, Sch name = SD_CD
# set_property PACKAGE_PIN A1 [get_ports {SD_CD}]
# set_property IOSTANDARD LVCMOS33 [get_ports {SD_CD}]
# # Pin name = IO_L9P_T1_DQS_AD7P_35, Sch name = SD_SCK
# set_property PACKAGE_PIN B1 [get_ports {SD_SCK}]
# set_property IOSTANDARD LVCMOS33 [get_ports {SD_SCK}]
# # Pin name = IO_L16N_T2_35, Sch name = SD_CMD
# set_property PACKAGE_PIN C1 [get_ports {SD_CMD}]
# set_property IOSTANDARD LVCMOS33 [get_ports {SD_CMD}]
# # Pin name = IO_L16P_T2_35, Sch name = SD_DAT[0]
# set_property PACKAGE_PIN C2 [get_ports {SD_DAT[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {SD_DAT[0]}]
# # Pin name = IO_L18N_T2_35, Sch name = SD_DAT[1]
# set_property PACKAGE_PIN E1 [get_ports {SD_DAT[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {SD_DAT[1]}]
# # Pin name = IO_L18P_T2_35, Sch name = SD_DAT[2]
# set_property PACKAGE_PIN F1 [get_ports {SD_DAT[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {SD_DAT[2]}]
# # Pin name = IO_L14N_T2_SRCC_35, Sch name = SD_DAT[3]
# set_property PACKAGE_PIN D2 [get_ports {SD_DAT[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {SD_DAT[3]}]

# #Accelerometer
# # Pin name = IO_L11P_T1_SRCC_15, Sch name = ACL_MISO
# set_property PACKAGE_PIN E15 [get_ports {ACL_MISO}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ACL_MISO}]
# # Pin name = IO_L5N_T0_AD9N_15, Sch name = ACL_MOSI
# set_property PACKAGE_PIN F14 [get_ports {ACL_MOSI}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ACL_MOSI}]
# # Pin name = IO_L14P_T2_SRCC_15, Sch name = ACL_SCLK
# set_property PACKAGE_PIN F15 [get_ports {ACL_SCLK}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ACL_SCLK}]
# # Pin name = IO_L12P_T1_MRCC_15, Sch name = ACL_CSN
# set_property PACKAGE_PIN D15 [get_ports {ACL_CSN}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ACL_CSN}]
# # Pin name = IO_L2P_T0_AD8P_15, Sch name = ACL_INT[1]
# set_property PACKAGE_PIN B13 [get_ports {ACL_INT[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ACL_INT[1]}]
# # Pin name = IO_L20P_T3_A20_15, Sch name = ACL_INT[2]
# set_property PACKAGE_PIN C16 [get_ports {ACL_INT[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ACL_INT[2]}]

# #Temperature Sensor
# # Pin name = IO_L1N_T0_AD0N_15, Sch name = TMP_SCL
# set_property PACKAGE_PIN C14 [get_ports {TMP_SCL}]
# set_property IOSTANDARD LVCMOS33 [get_ports {TMP_SCL}]
# # Pin name = IO_L12N_T1_MRCC_15, Sch name = TMP_SDA
# set_property PACKAGE_PIN C15 [get_ports {TMP_SDA}]
# set_property IOSTANDARD LVCMOS33 [get_ports {TMP_SDA}]
# # Pin name = IO_L6N_T0_VREF_15, Sch name = TMP_INT
# set_property PACKAGE_PIN D13 [get_ports {TMP_INT}]
# set_property IOSTANDARD LVCMOS33 [get_ports {TMP_INT}]
# # Pin name = IO_L2N_T0_AD8N_15, Sch name = TMP_CT
# set_property PACKAGE_PIN B14 [get_ports {TMP_CT}]
# set_property IOSTANDARD LVCMOS33 [get_ports {TMP_CT}]

# #Omnidirectional Microphone
# # Pin name = IO_25_35, Sch name = M_CLK
# set_property PACKAGE_PIN J5 [get_ports {M_CLK}]
# set_property IOSTANDARD LVCMOS33 [get_ports {M_CLK}]
# # Pin name = IO_L24N_T3_35, Sch name = M_DATA
# set_property PACKAGE_PIN H5 [get_ports {M_DATA}]
# set_property IOSTANDARD LVCMOS33 [get_ports {M_DATA}]
# # Pin name = IO_0_35, Sch name = M_LRSEL
# set_property PACKAGE_PIN F5 [get_ports {M_LRSEL}]
# set_property IOSTANDARD LVCMOS33 [get_ports {M_LRSEL}]

# #PWM Audio Amplifier
# # Pin name = IO_L4N_T0_15, Sch name = AUD_PWM
# set_property PACKAGE_PIN A11 [get_ports {AUD_PWM}]
# set_property IOSTANDARD LVCMOS33 [get_ports {AUD_PWM}]
# # Pin name = IO_L6P_T0_15, Sch name = AUD_SD
# set_property PACKAGE_PIN D12 [get_ports {AUD_SD}]
# set_property IOSTANDARD LVCMOS33 [get_ports {AUD_SD}]

#USB-RS232 Interface
# # Pin name = IO_L7P_T1_AD6P_35, Sch name = UART_TXD_IN
# set_property PACKAGE_PIN C4 [get_ports {UART_TXD_IN}]
# set_property IOSTANDARD LVCMOS33 [get_ports {UART_TXD_IN}]
# # Pin name = IO_L11N_T1_SRCC_35, Sch name = UART_RXD_OUT
# set_property PACKAGE_PIN D4 [get_ports {UART_RXD_OUT}]
# set_property IOSTANDARD LVCMOS33 [get_ports {UART_RXD_OUT}]
# # Pin name = IO_L12N_T1_MRCC_35, Sch name = UART_CTS
# set_property PACKAGE_PIN D3 [get_ports {UART_CTS}]
# set_property IOSTANDARD LVCMOS33 [get_ports {UART_CTS}]
# # Pin name = IO_L5N_T0_AD13N_35, Sch name = UART_RTS
# set_property PACKAGE_PIN E5 [get_ports {UART_RTS}]
# set_property IOSTANDARD LVCMOS33 [get_ports {UART_RTS}]

# #USB HID (PS/2)
# # Pin name = IO_L13P_T2_MRCC_35, Sch name = PS2_CLK
# set_property PACKAGE_PIN F4 [get_ports {PS2_CLK}]
# set_property IOSTANDARD LVCMOS33 [get_ports {PS2_CLK}]
# # Pin name = IO_L10N_T1_AD15N_35, Sch name = PS2_DATA
# set_property PACKAGE_PIN B2 [get_ports {PS2_DATA}]
# set_property IOSTANDARD LVCMOS33 [get_ports {PS2_DATA}]

# #SMSC Ethernet PHY
# # Pin name = IO_L11P_T1_SRCC_16, Sch name = ETH_MDC
# set_property PACKAGE_PIN C9 [get_ports {ETH_MDC}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ETH_MDC}]
# # Pin name = IO_L14N_T2_SRCC_16, Sch name = ETH_MDIO
# set_property PACKAGE_PIN A9 [get_ports {ETH_MDIO}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ETH_MDIO}]
# # Pin name = IO_L10P_T1_AD15P_35, Sch name = ETH_RSTN
# set_property PACKAGE_PIN B3 [get_ports {ETH_RSTN}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ETH_RSTN}]
# # Pin name = IO_L6N_T0_VREF_16, Sch name = ETH_CRSDV
# set_property PACKAGE_PIN D9 [get_ports {ETH_CRSDV}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ETH_CRSDV}]
# # Pin name = IO_L13N_T2_MRCC_16, Sch name = ETH_RXERR
# set_property PACKAGE_PIN C10 [get_ports {ETH_RXERR}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ETH_RXERR}]
# # Pin name = IO_L13P_T2_MRCC_16, Sch name = ETH_RXD[0]
# set_property PACKAGE_PIN C11 [get_ports {ETH_RXD[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ETH_RXD[0]}]
# # Pin name = IO_L19N_T3_VREF_16, Sch name = ETH_RXD[1]
# set_property PACKAGE_PIN D10 [get_ports {ETH_RXD[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ETH_RXD[1]}]
# # Pin name = IO_L11N_T1_SRCC_16, Sch name = ETH_TXEN
# set_property PACKAGE_PIN B9 [get_ports {ETH_TXEN}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ETH_TXEN}]
# # Pin name = IO_L14P_T2_SRCC_16, Sch name = ETH_TXD[0]
# set_property PACKAGE_PIN A10 [get_ports {ETH_TXD[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ETH_TXD[0]}]
# # Pin name = IO_L12N_T1_MRCC_16, Sch name = ETH_TXD[1]
# set_property PACKAGE_PIN A8 [get_ports {ETH_TXD[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ETH_TXD[1]}]
# # Pin name = IO_L11P_T1_SRCC_35, Sch name = ETH_REFCLK
# set_property PACKAGE_PIN D5 [get_ports {ETH_REFCLK}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ETH_REFCLK}]
# # Pin name = IO_L12P_T1_MRCC_16, Sch name = ETH_INTN
# set_property PACKAGE_PIN B8 [get_ports {ETH_INTN}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ETH_INTN}]

# #Quad SPI Flash
# # Pin name = IO_L1P_T0_D00_MOSI_14, Sch name = QSPI_DQ[0]
# set_property PACKAGE_PIN K17 [get_ports {QSPI_DQ[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {QSPI_DQ[0]}]
# # Pin name = IO_L1N_T0_D01_DIN_14, Sch name = QSPI_DQ[1]
# set_property PACKAGE_PIN K18 [get_ports {QSPI_DQ[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {QSPI_DQ[1]}]
# # Pin name = IO_L2P_T0_D02_14, Sch name = QSPI_DQ[2]
# set_property PACKAGE_PIN L14 [get_ports {QSPI_DQ[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {QSPI_DQ[2]}]
# # Pin name = IO_L2N_T0_D03_14, Sch name = QSPI_DQ[3]
# set_property PACKAGE_PIN M14 [get_ports {QSPI_DQ[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {QSPI_DQ[3]}]
# # Pin name = IO_L6P_T0_FCS_B_14, Sch name = QSPI_CSN
# set_property PACKAGE_PIN L13 [get_ports {QSPI_CSN}]
# set_property IOSTANDARD LVCMOS33 [get_ports {QSPI_CSN}]